node {
   // def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     // commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
      steps {
          echo "stage 2"
      }
   }
   stage('docker build/push') {
      steps{
          echo "third stage"
      }
   }
}
