pipeline {
    agent any
    
    stages {
        stage('Print Hello World 1') {
            steps {
                echo 'Hello World 1'
            }
        }
        
        stage('Print Hello World 2') {
            steps {
                echo 'Hello World 2'
            }
        }
    }
}
